image:
  file: .gitpod.Dockerfile
tasks:
  - name: Dev Server
    init: npm ci
    command: |
      npx cypress install
      npm run dev
ports:
  - port: 1234
    onOpen: open-preview
    name: Dev Server
