image:
  file: .gitpod.Dockerfile
tasks:
  - name: Vite Dev Server
    init: npm ci
    command: |
      npx cypress install
      npm run dev
ports:
  - port: 5173
    onOpen: open-preview
    name: Vite Dev Server
